language: bash

sudo: required

services:
  - docker

script:
  - make

after_success: |
  if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ("${TRAVIS_BRANCH}" == "master"  || -n "${TRAVIS_TAG}") ]]; then
    docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

    make release

    if [[ -n "${TRAVIS_TAG}" ]]; then
      export TAG="${TRAVIS_TAG}"
    fi
  fi
